import { useState } from 'react'
import { BookOpenCheck, Route, Sparkles } from 'lucide-react'
import http from '../services/http.service'

function LearningRoadmap() {
  const [targetRole, setTargetRole] = useState(''); const [skills, setSkills] = useState(''); const [roadmap, setRoadmap] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function generate(event) { event.preventDefault(); setLoading(true); setError(''); try { setRoadmap((await http.post('/api/decision-intelligence/candidate/learning-roadmap', { targetRole, requiredSkills: skills.split(',').map((skill) => skill.trim()).filter(Boolean) })).data) } catch (requestError) { setError(requestError.message || 'Unable to generate roadmap.') } finally { setLoading(false) } }
  return <main className="space-y-7 pb-12 animate-fade-in"><section className="rounded-3xl bg-gradient-to-br from-emerald-950 to-teal-900 p-7 text-white shadow-xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-emerald-300"><Route className="h-4 w-4" /> AI Learning Roadmap</p><h1 className="mt-4 text-3xl font-extrabold">Turn skill gaps into a plan.</h1><p className="mt-2 text-sm text-emerald-100">Compare a target role’s skills with your Digital Twin, then build portfolio evidence as you learn.</p><form onSubmit={generate} className="mt-6 grid gap-3 md:grid-cols-3"><input value={targetRole} onChange={(event) => setTargetRole(event.target.value)} placeholder="Target role, e.g. Backend Developer" className="rounded-2xl bg-white px-4 py-3 text-sm text-slate-800" /><input value={skills} onChange={(event) => setSkills(event.target.value)} placeholder="Required skills, comma separated" className="rounded-2xl bg-white px-4 py-3 text-sm text-slate-800 md:col-span-2" /><button className="w-fit rounded-2xl bg-emerald-300 px-5 py-3 text-sm font-bold text-emerald-950" disabled={loading}>{loading ? 'Building…' : 'Build roadmap'}</button></form></section>{error && <p className="rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{roadmap && <section className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Role readiness" value={`${roadmap.readiness}%`} /><Metric label="Known skills" value={roadmap.currentSkills.length} /><Metric label="Skills to build" value={roadmap.missingSkills.length} /></div>{roadmap.sequence.length ? <div className="space-y-4">{roadmap.sequence.map((step) => <article key={step.skill} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex gap-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-100 font-bold text-emerald-700">{step.order}</div><div><div className="flex flex-wrap gap-2"><h2 className="font-bold text-slate-900">{step.skill}</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-500">{step.duration}</span></div><p className="mt-2 text-sm text-slate-600">{step.objective}</p><p className="mt-2 text-sm text-emerald-700"><strong>Portfolio proof:</strong> {step.project}</p><p className="mt-2 text-xs text-slate-500">Evidence: {step.completionEvidence.join(' · ')}</p></div></div></article>)}</div> : <div className="rounded-3xl bg-white p-8 text-center shadow-sm"><BookOpenCheck className="mx-auto h-8 w-8 text-emerald-600" /><p className="mt-3 font-semibold text-slate-700">No skills were supplied yet.</p><p className="mt-1 text-sm text-slate-400">Paste the requirements from a target job to create a focused learning sequence.</p></div>}</section>}</main>
}
function Metric({ label, value }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-emerald-700">{value}</p></div> }
export default LearningRoadmap
